### ISSUE TITLE
celery connection refused errno 111

### ISSUE THREAD

**Issue by ak-24** [rakanalh/django-pushy#16]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 23, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 472, in run
    replies = I.run('ping', **kwargs)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 324, in run
    return self.do_call_method(args, **kwargs)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 346, in do_call_method
    callback=self.say_remote_command_reply)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/bin/celery.py", line 385, in call
    return getattr(i, method)(*args)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/app/control.py", line 100, in ping
    return self._request('ping')
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/celery/app/control.py", line 307, in broadcast
    limit, callback, channel=channel,
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/kombu/pidbox.py", line 283, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/kombu/connection.py", line 756, in default_channel
    self.connection
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/pankaj/myproject/myprojectenv/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 111] Connection refused

**Comment by rakanalh** [comment]
@ak-24, You should have provided more info about your problem. However, i suggest you go through this page http://docs.celeryproject.org/en/latest/index.html to make sure you've setup your project properly with celery and a broker of your choice.
